<<<<<<< HEAD
﻿//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitor.Locales {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Monitor.Locales.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Monitor 的本地化字符串。
        /// </summary>
        public static string Monitor {
            get {
                return ResourceManager.GetString("Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Metric 的本地化字符串。
        /// </summary>
        public static string Monitor_Metric {
            get {
                return ResourceManager.GetString("Monitor_Metric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPU 的本地化字符串。
        /// </summary>
        public static string Monitor_Metric_0 {
            get {
                return ResourceManager.GetString("Monitor_Metric_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RAM 的本地化字符串。
        /// </summary>
        public static string Monitor_Metric_1 {
            get {
                return ResourceManager.GetString("Monitor_Metric_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disk 的本地化字符串。
        /// </summary>
        public static string Monitor_Metric_2 {
            get {
                return ResourceManager.GetString("Monitor_Metric_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network 的本地化字符串。
        /// </summary>
        public static string Monitor_Metric_3 {
            get {
                return ResourceManager.GetString("Monitor_Metric_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Battery 的本地化字符串。
        /// </summary>
        public static string Monitor_Metric_4 {
            get {
                return ResourceManager.GetString("Monitor_Metric_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View the status of your PC 的本地化字符串。
        /// </summary>
        public static string Monitor_SingleMetric_Subtitle {
            get {
                return ResourceManager.GetString("Monitor_SingleMetric_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Single Metric 的本地化字符串。
        /// </summary>
        public static string Monitor_SingleMetric_Title {
            get {
                return ResourceManager.GetString("Monitor_SingleMetric_Title", resourceCulture);
            }
        }
    }
}
=======
﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitor.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Monitor.Locales.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor.
        /// </summary>
        public static string Monitor {
            get {
                return ResourceManager.GetString("Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric.
        /// </summary>
        public static string Monitor_Metric {
            get {
                return ResourceManager.GetString("Monitor_Metric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU.
        /// </summary>
        public static string Monitor_Metric_0 {
            get {
                return ResourceManager.GetString("Monitor_Metric_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAM.
        /// </summary>
        public static string Monitor_Metric_1 {
            get {
                return ResourceManager.GetString("Monitor_Metric_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk.
        /// </summary>
        public static string Monitor_Metric_2 {
            get {
                return ResourceManager.GetString("Monitor_Metric_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        public static string Monitor_Metric_3 {
            get {
                return ResourceManager.GetString("Monitor_Metric_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery.
        /// </summary>
        public static string Monitor_Metric_4 {
            get {
                return ResourceManager.GetString("Monitor_Metric_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the status of your PC.
        /// </summary>
        public static string Monitor_SingleMetric_Subtitle {
            get {
                return ResourceManager.GetString("Monitor_SingleMetric_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Metric.
        /// </summary>
        public static string Monitor_SingleMetric_Title {
            get {
                return ResourceManager.GetString("Monitor_SingleMetric_Title", resourceCulture);
            }
        }
    }
}
>>>>>>> parent of 15524c5 (Delete src directory)
