//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clock.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Clock.Locales.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock.
        /// </summary>
        public static string Clock {
            get {
                return ResourceManager.GetString("Clock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a clock for a city to check the time at that location.
        /// </summary>
        public static string Clock_Analog_Subtitle {
            get {
                return ResourceManager.GetString("Clock_Analog_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog I.
        /// </summary>
        public static string Clock_AnalogI_Title {
            get {
                return ResourceManager.GetString("Clock_AnalogI_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog II.
        /// </summary>
        public static string Clock_AnalogII_Title {
            get {
                return ResourceManager.GetString("Clock_AnalogII_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog III.
        /// </summary>
        public static string Clock_AnalogIII_Title {
            get {
                return ResourceManager.GetString("Clock_AnalogIII_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital.
        /// </summary>
        public static string Clock_Digital_Title {
            get {
                return ResourceManager.GetString("Clock_Digital_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use local time zone.
        /// </summary>
        public static string Clock_LocalTimeZone {
            get {
                return ResourceManager.GetString("Clock_LocalTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show seconds.
        /// </summary>
        public static string Clock_ShowSeconds {
            get {
                return ResourceManager.GetString("Clock_ShowSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time zone.
        /// </summary>
        public static string Clock_TimeZone {
            get {
                return ResourceManager.GetString("Clock_TimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24-hour time.
        /// </summary>
        public static string Clock_Use24Hours {
            get {
                return ResourceManager.GetString("Clock_Use24Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the time in multiple cities from around the world.
        /// </summary>
        public static string Clock_World_Subtitle {
            get {
                return ResourceManager.GetString("Clock_World_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Clock.
        /// </summary>
        public static string Clock_World_Title {
            get {
                return ResourceManager.GetString("Clock_World_Title", resourceCulture);
            }
        }
    }
}
