//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uWidgets.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("uWidgets.Locales.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Settings_About {
            get {
                return ResourceManager.GetString("Settings_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Settings_About_Actions {
            get {
                return ResourceManager.GetString("Settings_About_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a bug.
        /// </summary>
        public static string Settings_About_ReportBug {
            get {
                return ResourceManager.GetString("Settings_About_ReportBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub repository.
        /// </summary>
        public static string Settings_About_Repository {
            get {
                return ResourceManager.GetString("Settings_About_Repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit.
        /// </summary>
        public static string Settings_About_Repository_Action {
            get {
                return ResourceManager.GetString("Settings_About_Repository_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Settings_About_Version {
            get {
                return ResourceManager.GetString("Settings_About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Settings_Appearance {
            get {
                return ResourceManager.GetString("Settings_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string Settings_Appearance_AccentColor_Manual {
            get {
                return ResourceManager.GetString("Settings_Appearance_AccentColor_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string Settings_Appearance_AccentColor_Null {
            get {
                return ResourceManager.GetString("Settings_Appearance_AccentColor_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent color.
        /// </summary>
        public static string Settings_Appearance_AccentColor_Title {
            get {
                return ResourceManager.GetString("Settings_Appearance_AccentColor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Settings_Appearance_DarkMode_False {
            get {
                return ResourceManager.GetString("Settings_Appearance_DarkMode_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string Settings_Appearance_DarkMode_Null {
            get {
                return ResourceManager.GetString("Settings_Appearance_DarkMode_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the colors that appear in widget.
        /// </summary>
        public static string Settings_Appearance_DarkMode_Subtitle {
            get {
                return ResourceManager.GetString("Settings_Appearance_DarkMode_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your mode.
        /// </summary>
        public static string Settings_Appearance_DarkMode_Title {
            get {
                return ResourceManager.GetString("Settings_Appearance_DarkMode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark .
        /// </summary>
        public static string Settings_Appearance_DarkMode_True {
            get {
                return ResourceManager.GetString("Settings_Appearance_DarkMode_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevent accidental widget repositioning.
        /// </summary>
        public static string Settings_Appearance_LockPosition_Subtitle {
            get {
                return ResourceManager.GetString("Settings_Appearance_LockPosition_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock position.
        /// </summary>
        public static string Settings_Appearance_LockPosition_Title {
            get {
                return ResourceManager.GetString("Settings_Appearance_LockPosition_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevent accidental widget resizing.
        /// </summary>
        public static string Settings_Appearance_LockSize_Subtitle {
            get {
                return ResourceManager.GetString("Settings_Appearance_LockSize_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock size.
        /// </summary>
        public static string Settings_Appearance_LockSize_Title {
            get {
                return ResourceManager.GetString("Settings_Appearance_LockSize_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widgets elements appear in the same color.
        /// </summary>
        public static string Settings_Appearance_Monochrome_Subtitle {
            get {
                return ResourceManager.GetString("Settings_Appearance_Monochrome_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monochrome theme.
        /// </summary>
        public static string Settings_Appearance_Monochrome_Title {
            get {
                return ResourceManager.GetString("Settings_Appearance_Monochrome_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Settings_Appearance_Position {
            get {
                return ResourceManager.GetString("Settings_Appearance_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Settings_Appearance_Size {
            get {
                return ResourceManager.GetString("Settings_Appearance_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align widget position to grid.
        /// </summary>
        public static string Settings_Appearance_SnapPosition_Subtitle {
            get {
                return ResourceManager.GetString("Settings_Appearance_SnapPosition_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap position.
        /// </summary>
        public static string Settings_Appearance_SnapPosition_Title {
            get {
                return ResourceManager.GetString("Settings_Appearance_SnapPosition_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align widget size to grid.
        /// </summary>
        public static string Settings_Appearance_SnapSize_Subtitle {
            get {
                return ResourceManager.GetString("Settings_Appearance_SnapSize_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap size.
        /// </summary>
        public static string Settings_Appearance_SnapSize_Title {
            get {
                return ResourceManager.GetString("Settings_Appearance_SnapSize_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Settings_Appearance_Theme {
            get {
                return ResourceManager.GetString("Settings_Appearance_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widgets appear translucent.
        /// </summary>
        public static string Settings_Appearance_Transparency_Subtitle {
            get {
                return ResourceManager.GetString("Settings_Appearance_Transparency_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparency effects.
        /// </summary>
        public static string Settings_Appearance_Transparency_Title {
            get {
                return ResourceManager.GetString("Settings_Appearance_Transparency_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal distance between widgets.
        /// </summary>
        public static string Settings_Appearance_WidgetMargin_Subtitle {
            get {
                return ResourceManager.GetString("Settings_Appearance_WidgetMargin_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widget margin.
        /// </summary>
        public static string Settings_Appearance_WidgetMargin_Title {
            get {
                return ResourceManager.GetString("Settings_Appearance_WidgetMargin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of the small widget.
        /// </summary>
        public static string Settings_Appearance_WidgetSize_Subtitle {
            get {
                return ResourceManager.GetString("Settings_Appearance_WidgetSize_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widget size.
        /// </summary>
        public static string Settings_Appearance_WidgetSize_Title {
            get {
                return ResourceManager.GetString("Settings_Appearance_WidgetSize_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Settings_General {
            get {
                return ResourceManager.GetString("Settings_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Settings_General_Actions {
            get {
                return ResourceManager.GetString("Settings_General_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Settings_General_Exit_Action {
            get {
                return ResourceManager.GetString("Settings_General_Exit_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit the application.
        /// </summary>
        public static string Settings_General_Exit_Title {
            get {
                return ResourceManager.GetString("Settings_General_Exit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_General_Language {
            get {
                return ResourceManager.GetString("Settings_General_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uWidgets will appear in this language.
        /// </summary>
        public static string Settings_General_Language_Subtitle {
            get {
                return ResourceManager.GetString("Settings_General_Language_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display language.
        /// </summary>
        public static string Settings_General_Language_Title {
            get {
                return ResourceManager.GetString("Settings_General_Language_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string Settings_General_Restart_Action {
            get {
                return ResourceManager.GetString("Settings_General_Restart_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the application.
        /// </summary>
        public static string Settings_General_Restart_Title {
            get {
                return ResourceManager.GetString("Settings_General_Restart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup.
        /// </summary>
        public static string Settings_General_Startup {
            get {
                return ResourceManager.GetString("Settings_General_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to run the application as Administrator to edit this setting.
        /// </summary>
        public static string Settings_General_Startup_Subtitle {
            get {
                return ResourceManager.GetString("Settings_General_Startup_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run on startup.
        /// </summary>
        public static string Settings_General_Startup_Title {
            get {
                return ResourceManager.GetString("Settings_General_Startup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Update_Download {
            get {
                return ResourceManager.GetString("Update_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        public static string Update_Later {
            get {
                return ResourceManager.GetString("Update_Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip This Version.
        /// </summary>
        public static string Update_SkipThisVersion {
            get {
                return ResourceManager.GetString("Update_SkipThisVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Update.
        /// </summary>
        public static string Update_SoftwareUpdate {
            get {
                return ResourceManager.GetString("Update_SoftwareUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uWidgets {0} is available to download.
        /// </summary>
        public static string Update_UpdateFormat {
            get {
                return ResourceManager.GetString("Update_UpdateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widget.
        /// </summary>
        public static string Widget {
            get {
                return ResourceManager.GetString("Widget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Widget_Edit {
            get {
                return ResourceManager.GetString("Widget_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit widgets.
        /// </summary>
        public static string Widget_OpenSettings {
            get {
                return ResourceManager.GetString("Widget_OpenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove widget.
        /// </summary>
        public static string Widget_Remove {
            get {
                return ResourceManager.GetString("Widget_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Widget_Save {
            get {
                return ResourceManager.GetString("Widget_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Widget_Size {
            get {
                return ResourceManager.GetString("Widget_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Large.
        /// </summary>
        public static string Widget_Size_ExtraLarge {
            get {
                return ResourceManager.GetString("Widget_Size_ExtraLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        public static string Widget_Size_Large {
            get {
                return ResourceManager.GetString("Widget_Size_Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string Widget_Size_Medium {
            get {
                return ResourceManager.GetString("Widget_Size_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        public static string Widget_Size_Small {
            get {
                return ResourceManager.GetString("Widget_Size_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widgets.
        /// </summary>
        public static string Widgets {
            get {
                return ResourceManager.GetString("Widgets", resourceCulture);
            }
        }
    }
}
