//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weather.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Weather.Locales.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        public static string Weather {
            get {
                return ResourceManager.GetString("Weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Weather_Code_0 {
            get {
                return ResourceManager.GetString("Weather_Code_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostly clear.
        /// </summary>
        public static string Weather_Code_1 {
            get {
                return ResourceManager.GetString("Weather_Code_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partly cloudy.
        /// </summary>
        public static string Weather_Code_2 {
            get {
                return ResourceManager.GetString("Weather_Code_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloudy.
        /// </summary>
        public static string Weather_Code_3 {
            get {
                return ResourceManager.GetString("Weather_Code_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fog.
        /// </summary>
        public static string Weather_Code_45 {
            get {
                return ResourceManager.GetString("Weather_Code_45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fog.
        /// </summary>
        public static string Weather_Code_48 {
            get {
                return ResourceManager.GetString("Weather_Code_48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drizzle.
        /// </summary>
        public static string Weather_Code_51 {
            get {
                return ResourceManager.GetString("Weather_Code_51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drizzle.
        /// </summary>
        public static string Weather_Code_53 {
            get {
                return ResourceManager.GetString("Weather_Code_53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drizzle.
        /// </summary>
        public static string Weather_Code_55 {
            get {
                return ResourceManager.GetString("Weather_Code_55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezing drizzle.
        /// </summary>
        public static string Weather_Code_56 {
            get {
                return ResourceManager.GetString("Weather_Code_56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezing drizzle.
        /// </summary>
        public static string Weather_Code_57 {
            get {
                return ResourceManager.GetString("Weather_Code_57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain.
        /// </summary>
        public static string Weather_Code_61 {
            get {
                return ResourceManager.GetString("Weather_Code_61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain.
        /// </summary>
        public static string Weather_Code_63 {
            get {
                return ResourceManager.GetString("Weather_Code_63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy rain.
        /// </summary>
        public static string Weather_Code_65 {
            get {
                return ResourceManager.GetString("Weather_Code_65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezing rain.
        /// </summary>
        public static string Weather_Code_66 {
            get {
                return ResourceManager.GetString("Weather_Code_66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezing rain.
        /// </summary>
        public static string Weather_Code_67 {
            get {
                return ResourceManager.GetString("Weather_Code_67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow.
        /// </summary>
        public static string Weather_Code_71 {
            get {
                return ResourceManager.GetString("Weather_Code_71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow.
        /// </summary>
        public static string Weather_Code_73 {
            get {
                return ResourceManager.GetString("Weather_Code_73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy snow.
        /// </summary>
        public static string Weather_Code_75 {
            get {
                return ResourceManager.GetString("Weather_Code_75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow.
        /// </summary>
        public static string Weather_Code_77 {
            get {
                return ResourceManager.GetString("Weather_Code_77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain showers.
        /// </summary>
        public static string Weather_Code_80 {
            get {
                return ResourceManager.GetString("Weather_Code_80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain showers.
        /// </summary>
        public static string Weather_Code_81 {
            get {
                return ResourceManager.GetString("Weather_Code_81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain showers.
        /// </summary>
        public static string Weather_Code_82 {
            get {
                return ResourceManager.GetString("Weather_Code_82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow showers.
        /// </summary>
        public static string Weather_Code_85 {
            get {
                return ResourceManager.GetString("Weather_Code_85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow showers.
        /// </summary>
        public static string Weather_Code_86 {
            get {
                return ResourceManager.GetString("Weather_Code_86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunderstorm.
        /// </summary>
        public static string Weather_Code_95 {
            get {
                return ResourceManager.GetString("Weather_Code_95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunderstorm.
        /// </summary>
        public static string Weather_Code_96 {
            get {
                return ResourceManager.GetString("Weather_Code_96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunderstorm.
        /// </summary>
        public static string Weather_Code_99 {
            get {
                return ResourceManager.GetString("Weather_Code_99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See the current weather conditions and forecast for a location.
        /// </summary>
        public static string Weather_Forecast_Subtitle {
            get {
                return ResourceManager.GetString("Weather_Forecast_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecast.
        /// </summary>
        public static string Weather_Forecast_Title {
            get {
                return ResourceManager.GetString("Weather_Forecast_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Weather_Location {
            get {
                return ResourceManager.GetString("Weather_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string Weather_Units {
            get {
                return ResourceManager.GetString("Weather_Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celsius.
        /// </summary>
        public static string Weather_Units_Celsius {
            get {
                return ResourceManager.GetString("Weather_Units_Celsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fahrenheit.
        /// </summary>
        public static string Weather_Units_Fahrenheit {
            get {
                return ResourceManager.GetString("Weather_Units_Fahrenheit", resourceCulture);
            }
        }
    }
}
